
      
workflows:
  android-workflow:
    name: Free Fire Tournament App
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Generate Android Folder and Build
        script: |
          flutter create --platforms=android .
          flutter packages pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
